config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get '/mision-vision-principios' => 'static_pages#mvp', as: 'mvp'
  get '/mensaje-de-la-direccion' => 'static_pages#mensaje_direccion', as: 'mensaje_direccion'
  get '/logros' => 'static_pages#logros', as: 'logros'
  get '/reconocimientos-y-certificaciones' => 'static_pages#ryc', as: 'ryc'
  get '/ram' => 'static_pages#ram', as: 'ram'
  get '/tijuana-waterkeeper' => 'static_pages#tj_waterkeeper', as: 'tj_waterkeeper'
  get '/corredores-ecologicos-transfronterizos' => 'static_pages#cet', as: 'cet'
  get '/salvemos-la-playa' => 'static_pages#salvemos_playa', as: 'salvemos_playa'
  get '/eventos' => 'static_pages#eventos', as: 'eventos'
  get '/donativos' => 'static_pages#donativos', as: 'donativos'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def mvp
  end

  def mensaje_direccion
  end

  def logros
  end

  def ryc
  end

  def ram
  end

  def tj_waterkeeper
  end

  def cet
  end

  def salvemos_playa
  end

  def eventos
  end

  def donativos
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer pfea-blue white-text">
    <div class="container">
        <div class="row">
            <div class="col s12 m4 l4 center">
                <%= image_tag "pfea_wh.png" %>
            </div>
            <div class="col s12 m4 l4">
              <form action="#" method="GET">
                    <div class="input-field">
                        <input placeholder="Nombre" type="text">
                    </div>
                    <div class="input-field">
                        <input placeholder="Correo electrónico" type="text">
                    </div>
                    <div class="input-field">
                        <textarea placeholder="Mensaje" class="materialize-textarea"></textarea>
                    </div>
                    <button type="submit" class="btn col s12 white black-text">Enviar</button>
                </form>
            </div>
            <div class="col s12 m4 l4">
                <p><i class="material-icons medium">place</i> Volcán # 632, Secc. Monumental, Playas de Tijuana, Tijuana, B.C., México</p>
                <p><i class="material-icons medium">phone</i> Tel. (664) 630.05.90 | info@pfea.org</p>
                <p><i class="material-icons medium">mail</i> info@pfea.org</p>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            &copy; 2016 PFEA A.C.
        </div>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="pfea-white">
  <div class="nav-wrapper container">
    <!-- Navbar -->
    <a href="{% url 'pfea_app:index' %}" class="brand-logo">
      <%= image_tag "pfea_logo-2.png", class: "logo small" %>
    </a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li>
        <%= link_to "Inicio", root_url %>
      </li>
      <li>
        <a class="dropdown-button" data-beloworigin="true" href="#" data-activates="quienes-somos-dropdown">
          Quiénes somos
          <i class="material-icons right">arrow_drop_down</i>
        </a>
      <li>
        <a class="dropdown-button" data-beloworigin="true" href="#" data-activates="programas-dropdown">
          Programas
          <i class="material-icons right">arrow_drop_down</i>
        </a>
      </li>
      <li>
        <%= link_to "Eventos", eventos_url %>
      </li>
      <li>
        <a class="dropdown-button" data-beloworigin="true" href="#" data-activates="apoyanos-dropdown">
          Apóyanos
          <i class="material-icons right">arrow_drop_down</i>
        </a>
      </li>
    </ul>

    <!-- SideNav -->
    <ul class="side-nav" id="mobile-demo">
      <!-- Inicio -->
      <li>
        <%= link_to "Inicio", root_url%>
      </li>
      <!-- Quienes somos -->
      <li class="no-padding">
        <ul class="collapsible collapsible-accordion"><li>
        <a class="collapsible-header">
          Quiénes somos
        </a>
        <div class="collapsible-body">
          <ul>
            <li>
              <%= link_to "Misión, Visión y Principios", mvp_url%>
            </li>
            <li>
              <%= link_to "Mensaje de la Dirección", mensaje_direccion_url%>
            </li>
            <li>
              <%= link_to "Logros", logros_url%>
            </li>
            <li>
              <%= link_to "Reconocimientos y Certificaciones", ryc_url%>
            </li>
          </ul>
        </div>
        </li></ul>
      </li>
      <!-- Proramas -->
      <li class="no-padding">
        <ul class="collapsible collapsible-accordion"><li>
        <a class="collapsible-header">
          Programas
        </a>
        <div class="collapsible-body">
          <ul>
            <li>
              <%= link_to "Restaurantes Amigos del Mar", ram_url%>
            </li>
            <li>
              <%= link_to "Tijuana Waterkeeper", tj_waterkeeper_url%>
            </li>
            <li>
              <%= link_to "Corredores Ecológicos", cet_url%>
            </li>
            <li>
              <%= link_to "Salvemos la Playa", salvemos_playa_url%>
            </li>
          </ul>
        </div>
        </li></ul>
      </li>
      <!-- Eventos -->
      <li>
        <%= link_to "Eventos", eventos_url %>
      </li>
      <!-- Apoyanos -->
      <li class="no-padding">
        <ul class="collapsible collapsible-accordion"><li>
        <a class="collapsible-header">
          Apóyanos
        </a>
        <div class="collapsible-body">
          <ul>
            <li>
              <%= link_to "Donativos", donativos_url%>
            </li>
          </ul>
        </div>
        </li></ul>
      </li>
    </ul>

  </div>
</nav>

<ul id="quienes-somos-dropdown" class="dropdown-content">
  <li>
    <%= link_to "Misión, Visión y Principios", mvp_url%>
  </li>
  <li>
    <%= link_to "Mensaje de la Dirección", mensaje_direccion_url%>
  </li>
  <li>
    <%= link_to "Logros", logros_url%>
  </li>
  <li>
    <%= link_to "Reconocimientos y Certificaciones", ryc_url%>
  </li>
</ul>

<ul id="programas-dropdown" class="dropdown-content">
  <li>
    <%= link_to "Restaurantes Amigos del Mar", ram_url%>
  </li>
  <li>
    <%= link_to "Tijuana Waterkeeper", tj_waterkeeper_url%>
  </li>
  <li>
    <%= link_to "Corredores Ecológicos", cet_url%>
  </li>
  <li>
    <%= link_to "Salvemos la Playa", salvemos_playa_url%>
  </li>
</ul>

<ul id="apoyanos-dropdown" class="dropdown-content">
  <li>
    <%= link_to "Donativos", donativos_url%>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto Fronterizo de Educación Ambiental</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>

    <%= stylesheet_link_tag "pfea" %>
    <%= stylesheet_link_tag "pfea.colors" %>
    <%= stylesheet_link_tag "pfea.footer" %>
    <%= stylesheet_link_tag "pfea.icons" %>
    <%= stylesheet_link_tag "pfea.images" %>
    <%= stylesheet_link_tag "pfea.navbar" %>
    <%= stylesheet_link_tag "pfea.parallax" %>
    <%= stylesheet_link_tag "pfea.widgets" %>
  </head>

  <body>

    <%= render "layouts/navbar" %>

    <div class="main">
    <%= yield %>
    </div>

    <%= render "layouts/footer" %>

    <%= javascript_include_tag "pfea-script" %>
  </body>
</html>

app/views/static_pages/cet.html.erb
<!-- Parallax -->
<div class="parallax-container custom no-margin">
  <div class="parallax-content">
    <div class="parallax">
      <%= image_tag "Arroyo-Alamar-03.jpg" %>
    </div>
    <div class="container">
      <div class="row">
        <div class="col s12 m12 l12">
          <div class="text-container small valign-wrapper">
            <h3 class="center-block center">Corredores ecológicos transfronterizos</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="parallax-title left-align pfea-green"></div>
</div>

<!-- Que es -->
<div class="container default-margin">
  <div class="row">
    <div class="col s12 m12 l12">
      <h3>¿Qué es?</h3>
      <div class="divider"></div>
      <br>
      <div class="row">
        <div class="col s12 m4 l4">
          <div class="row">
            <%= image_tag "cet_big.png", class: "logo mid" %>
          </div>
        </div>
        <div class="col s12 m8 l8">
          <div class="row">
            <h4>Corredores Ecológicos Transfronterizos</h4>
          </div>
          <div class="row">
            <h5>Trabajamos para proteger las áreas naturales y espacios abiertos interconectados que brindan servicios ambientales al a cuenca del Río Tijuana en su naturaleza binacional, por sus beneficios para la comunidad y los ecosistemas.</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container default-margin">
  <div class="row">
    <div class="col s12 m8 l8">
      <h4>Proyectos</h4>
      <div class="divider"></div>
      <p><i class="material-icons smaller pfea-orange-text">send</i> Arroyo Alamar</p>
      <p><i class="material-icons smaller pfea-orange-text">send</i> Parque de Conservación Cañada de los Sauces</p>
    </div>
  </div>
</div>

app/views/static_pages/donativos.html.erb
<!-- Parallax -->
<div class="parallax-container custom no-margin">
  <div class="parallax-content">
    <div class="parallax">
      <%= image_tag "donativos.jpg" %>
    </div>
    <div class="container">
      <div class="row">
        <div class="col s12 m12 l12">
          <div class="text-container small valign-wrapper">
            <h3 class="center-block center">Donativos</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="parallax-title left-align pfea-blue"></div>
</div>

<div class="container default-padding">
  <div class="row">
    <h3>PayPal</h3>
    <div class="divider"></div>
    <div class="row">
      <div class="col s12 m6 l6">
        <p>Para hacer un donativo en moneda nacional da clic aquí:</p>
        <div>
          <form style="max-height: 70px!important;" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input name="cmd" type="hidden" value="_s-xclick" /><br />
            <input name="hosted_button_id" type="hidden" value="XB5N8KFLKRNR6" /><br />
            <input style="margin-top: -75px!important;" alt="PayPal, la forma más segura y rápida de pagar en línea." name="submit" src="https://www.paypalobjects.com/es_XC/MX/i/btn/btn_donateCC_LG.gif" type="image" /><br />
            <img src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" alt="" width="1" height="1" border="0" />
          </form>
        </div>
      </div>
      <div class="col s12 m6 l6">
        <p>To place a donation in USA dollars click here:</p>
        <div>
          <form style="max-height: 70px!important;" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input name="cmd" type="hidden" value="_s-xclick" /><br />
            <input name="hosted_button_id" type="hidden" value="ZRZ4PGXDZTC6S" /><br />
            <input style="margin-top: -75px!important;" alt="PayPal - The safer, easier way to pay online!" name="submit" src="https://www.paypalobjects.com/en_US/MX/i/btn/btn_donateCC_LG.gif" type="image" /><br />
            <img src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" alt="" width="1" height="1" border="0" />
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m12 l12">
      <h3>Inbursa</h3>
      <div class="divider"></div>
      <p>Banco Inbursa, S.A.</p>
      <p>Proyecto Fronterizo de Educación Ambiental A.C.</p>
      <p>CLAVE: 036028500118361394</p>
    </div>
  </div>
</div>

app/views/static_pages/eventos.html.erb
<div class="container center">
  <div class="row section">
    <div id="calendar"></div>
  </div>
</div>

app/views/static_pages/index.html.erb
<!-- Parallax -->
<div class="parallax-container custom no-margin">
  <div class="parallax-content">
    <div class="parallax">
      <%= image_tag "FRONTERA_NORTE.jpg" %>
    </div>
    <div class="container">
      <div class="row">
        <div class="col m6 l6"></div>
        <div class="col s12 m6 l6">
          <div class="text-container small valign-wrapper">
            <h4 class="center-block">25 años protegiendo nuestro océano, arroyos y costas</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="parallax-title left-align pfea-blue"></div>
</div>

<!-- Programas -->
<div class="container default-margin">
  <div class="row">
    <div class="col m12 l4 center valign-wrapper">
      <div class="center-block">
        <%= image_tag "tw.png", width: 100 %>
        <h5>Tijuana Waterkeeper</h5>
        <p>Te informamos semanalmente sobre la calidad del agua en la playa, para uso recreativo.</p>
      </div>
    </div>
    <div class="col m12 l4 center valign-wrapper">
      <div class="center-block">
        <%= image_tag "R.A.M._Logo-LetraBlanca.png", width: 100 %>
        <h5>Restaurante Amigo del Mar</h5>
        <p>Te enteramos de los graves impactos que ocasionan los plásticos desechables en el océano y las alternativas para prevenirlos.</p>
      </div>
    </div>
    <div class="col m12 l4 center valign-wrapper">
      <div class="center-block">
        <%= image_tag "cet_big.png", width: 100 %>
        <h5>Corredores Ecológicos Transfronterizos</h5>
        <p>Representamos tus inquietudes y propuestas en los Comités ciudadanos que se encargan de garantizar que se respeten tus derechos a un ambiente sano.</p>
      </div>
    </div>
  </div>
</div>

<!-- Estadisticas -->
<div class="parallax-container custom center no-margin">
  <div class="parallax">
    <%= image_tag "Fondo3_fixed.jpg" %>
  </div>
  <div class="overlay dark-blue"></div>
  <div class="container statistics-widget white-text valign-wrapper">
    <div class="row">
      <div class="col s12 m6 l3">
        <%= image_tag "icon-4.png" %>
        <h4 class="text-bold">70 ha</h4>
        <p>Rescate de ecosistema ripario</p>
      </div>
      <div class="col s12 m6 l3">
        <%= image_tag "icon-5.png" %>
        <h4 class="text-bold">366</h4>
        <p>Muestreos de calidad de agua</p>
      </div>
      <div class="col s12 m6 l3">
        <%= image_tag "icon-1.png" %>
        <h4 class="text-bold">220,000kg</h4>
        <p>Residiuos sólidos retirados de playas, cañadas y arroyos</p>
      </div>
      <div class="col s12 m6 l3">
        <%= image_tag "icon-2.png" %>
        <h4 class="text-bold">45,000</h4>
        <p>Voluntarios participantes en salvemos la playa</p>
      </div>
    </div>
  </div>
  <div class="parallax-title center pfea-orange"></div>
</div>

<!-- Suscripción -->
<div class="container center default-margin default-padding">
  <div class="row">
    <div class="col s12 m12 l12 center-block">
      <h4>Apóyanos como voluntario</h4>
      <div class="divider"></div>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m12 l12">
      <p class="text-bold">El sueño de una frontera limpia y conciente solo puede hacerse realidad con tu apoyo</p>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m12 l12">
      <a class="waves-effect waves-light btn-large pfea-green" href="{% url 'pfea_app:voluntarios' %}">Apóyanos</a>
    </div>
  </div>
</div>

<!-- Parallax -->
<div class="parallax-container custom no-margin">
  <div class="parallax-content">
    <div class="parallax">
      <%= image_tag "DSCN5751.jpg" %>
    </div>
    <div class="container">
      <div class="row">
        <div class="col s12 m6 l6">
          <div class="text-container small valign-wrapper">
            <p class="center-block title">Trabajamos para proteger las áreas naturales y espacios abiertos que brindan servicios ambientales a la cuenca del Río Tijuana, por sus beneficios para la comunidad y los ecosistemas</p>
          </div>
        </div>
        <div class="col m6 l6"></div>
      </div>
    </div>
  </div>
  <div class="parallax-title left-align pfea-green"></div>
</div>

<!-- Noticias, Videos y Facebook -->
<div class="container center default-margin default-padding">
  <div class="row">
    <div class="col s12 m12 l12">
      <h4>Ultimas Noticias</h4>
      <div class="divider"></div>
    </div>
  </div>
  <div class="row">
    {% for new in news %}
      <div class="col s12 m4 l4">
        <div class="card medium">
          <div class="card-content">
            <span class="card-title">{{ new.title|safe }}</span>
          </div>
          <div class="card-action">
            <a href="{{ new.link }}">Ver más</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="row">
    <div class="col s12 m7 l7">
      <iframe width="100%" height="420" src="https://www.youtube.com/embed/YJycx3tsGX4"></iframe>
    </div>
    <div class="col s12 m5 l5">
      <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fpfea.org&amp;tabs=timeline&amp;width=340&amp;height=420&amp;small_header=true&amp;adapt_container_width=true&amp;hide_cover=false&amp;show_facepile=true&amp;appId" width="340" height="420" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowtransparency="true" class="iframe-class"></iframe>
    </div>
  </div>
</div>

<!-- Mapa -->
<iframe style="border: 0; width: 100%;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3363.8539109808767!2d-117.12374408529966!3d32.53004850384506!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80d94ba6b171d2fb%3A0x11ca295a1c440f0f!2sCalle+del+Volcan+632%2C+Playas%2C+Monumental%2C+Tijuana%2C+B.C.!5e0!3m2!1ses!2smx!4v1458275792589" allowfullscreen="allowfullscreen" width="300" height="315" frameborder="0"></iframe>

app/views/static_pages/logros.html.erb
<div class="parallax-container custom no-margin">
  <div class="parallax-content">
    <div class="parallax">
      <%= image_tag "margarita-02.jpg" %>
    </div>
    <div class="container">
      <div class="row">
        <div class="col s12 m12 l12">
          <div class="text-container small valign-wrapper">
            <h3 class="center-block center">Logros</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="parallax-title left-align pfea-green"></div>
</div>
<br>
<div class="container">
  <div class="row">
    <div class="col s12 m12 l12">
      <h3>Lo que hicimos</h3>
      <div class="divider"></div>
      <p><i class="material-icons smaller pfea-blue-text">send</i> Incidimos en la normatividad federal para lograr que pudieran ser donatarias autorizadas las organizaciones ambientalistas dedicadas a otros temas aparte de la conservación de especies.</p>
      <p><i class="material-icons smaller pfea-blue-text">send</i> Formamos a una nueva generación  de líderes jóvenes ambientalistas en Tijuana.</p>
      <p><i class="material-icons smaller pfea-blue-text">send</i> Produjimos un currículo inédito especializado en los ecosistemas costeros de esta cuenca para impartir talleres de educación ambiental. </p>
      <p><i class="material-icons smaller pfea-blue-text">send</i> Fuimos promoventes pioneros del derecho a la información ambiental incidiendo en la normatividad federal y del estado y municipios de B.C.</p>
      <p><i class="material-icons smaller pfea-blue-text">send</i> Organizamos primera iniciativa ciudadana de vinculación entre mas de 1,500 ambientalistas de los 10 estados fronterizos de ambos lados de la frontera para hablar sobre temas ambientales.</p>
      <p><i class="material-icons smaller pfea-blue-text">send</i> Logramos la movilización de mas de 45,000 voluntarios para la limpieza y cuidado de las playas, arroyos y cañadas a escala estatal y remoción 220 toneladas a lo largo de 15 años.</p>
      <p><i class="material-icons smaller pfea-blue-text">send</i> Conducimos el primero y único  programa de monitoreo de cumplimiento de los gobiernos municipales y del estado con sus obligaciones de transparencia de información pública.</p>
      <p><i class="material-icons smaller pfea-blue-text">send</i> Operamos el primer laboratorio ciudadano de Baja California que genera avisos sistemáticos al público sobre la seguridad de la calidad de las aguas costeras para uso recreativo.</p>
      <p><i class="material-icons smaller pfea-blue-text">send</i> Somos líderes en el rescate de 35 ha. de ecosistema ripario del Arroyo Alamar y el Parque de Conservación Cañada de los Sauces.</p>
      <p><i class="material-icons smaller pfea-blue-text">send</i> Ayudamos a preservar el hábitat de especies en peligro de extinción y amenazadas, como son el pelícano café, el lobo marino y el delfín y otras que transitan frente a nuestras costas.</p>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m12 l12">
      <h3>Lo que hacemos</h3>
      <div class="divider"></div>
    </div>
    <div class="col s6 m6 l6">
      <h5>Visitante de la playa</h5>
      <p><i class="material-icons smaller pfea-green-text">send</i> Te informamos semanalmente sobre la calidad del agua de la playa, para uso recreativo.</p>
      <p><i class="material-icons smaller pfea-green-text">send</i> Patrullamos la playa continuamente para advertir alguna anomalía ambiental.</p>
    </div>
    <div class="col s6 m3 l6">
      <h5>Jóven</h5>
      <p><i class="material-icons smaller pfea-orange-text">send</i> Te capacitamos como líder ambiental juvenil de tu escuela y tu colonia.</p>
      <p><i class="material-icons smaller pfea-orange-text">send</i> Te capacitamos como capitán de sitio para las campañas de limpieza “Salvemos la Playa”.</p>
      <p><i class="material-icons smaller pfea-orange-text">send</i> Te ofrecemos un espacio de aprendizaje donde liberar tus horas de servicio social.</p>
    </div>
    <div class="col s6 m6 l6">
      <h5>Vecinos, líderes comunitarios, maestros</h5>
      <p><i class="material-icons smaller pfea-orange-text">send</i> Te asesoramos en tus gestiones por preservar ecosistemas y biodiversidad bajo amenaza.</p>
      <p><i class="material-icons smaller pfea-orange-text">send</i> Te enseñamos sobre el valor de las especies y el ecosistema costero y ribereño que nos rodea.</p>
      <p><i class="material-icons smaller pfea-orange-text">send</i> Te hacemos llegar información ambiental relevante, interesante y de manera constante.</p>
      <p><i class="material-icons smaller pfea-orange-text">send</i> Representamos tus inquietudes y propuestas en los Comités ciudadanos que se encargan de garantizar que se respeten tus derechos a un ambiente sano.</p>
    </div>
    <div class="col s6 m6 l6">
      <h5>Dueño y cliente de restaurantes</h5>
      <p><i class="material-icons smaller pfea-green-text">send</i> Te otorgamos una certificación como Restaurante Amigo Del Mar.</p>
      <p><i class="material-icons smaller pfea-green-text">send</i> Te enteramos de los graves impactos que ocasionan los plásticos desechables en el océano y las alternativas para prevenirlos.</p>
    </div>
  </div>
</div>

app/views/static_pages/mensaje_direccion.html.erb
<div class="parallax-container custom no-margin">
  <div class="parallax-content">
    <div class="parallax">
      <%= image_tag "Fondo3.jpg" %>
    </div>
    <div class="container">
      <div class="row">
        <div class="col s12 m12 l12">
          <div class="text-container small valign-wrapper">
            <h3 class="center-block center">Mensaje de la Dirección</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="parallax-title left-align pfea-blue"></div>
</div>

<div class="container just text-justified" style="padding: 30px 0;">
  <div class="row">
    <div class="col s4 m4 l4">
      <%= image_tag "margarita.jpeg", class: "logo mid",
                                        style: "width: 100%; min-height: 450px;" %>
    </div>
    <div class="col s8 m8 l8">
      <p>Es para mi un gusto el poder presentar ante ustedes este nuevo espacio de intercomunicación, con el que se pretende mostrar lo que ha sido a lo largo de 23 años el camino recorrido por Proyecto Fronterizo de Educación Ambiental A.C. (PFEA), un camino que refleja la historia y esfuerzo de un grupo de profesionales comprometidos, que hicieron de una idea una realidad, y compartirles día a día lo que hacemos e invitarlos a sumarse a nuestra visión del futuro.</p>
      <p>Siempre he creído que la mayor riqueza del individuo son los sueños que anhelamos alcanzar. Mi sueño personal es que todos podamos disfrutar de nuestra playa, un lugar mágico y punto de encuentro, hoy y mañana, como lo hice de niña, creciendo en una comunidad costera. Como Directora de PFEA, mi sueño es ver una Tijuana con sus rìos llenos de vida y su costa vibrante y sana. En este sentido, el mayor desafìo ha sido lograr que nuestra comunidad reconozca, primeramente, que vivimos en una ciudad ribereña y costera, y luego, que es el deber de todos preservar y proteger la riqueza que se encuentra en nuestros arroyos y costas. La protecciòn de servicios ambientales que estas fuentes de vida brindan al espacio que habitamos, es un paso fundamental para que sus habitantes gocen de calidad de vida y Tijuana se realice en todos los demás aspectos.</p>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m12 l12">
      <p>Quizás debido a este reto, la trayectoria de Proyecto Fronterizo haya resultado ser una aventura tan emocionante y rica en enseñanzas tanto de formaciòn ciudadana como de conocimiento ambiental; una verdadera escuela sobre las formas de incidir en la política e influir positivamente en las conductas de la comunidad a la que servimos. He tenido la gran fortuna de contar con un equipo de trabajo de verdaderos guerreros atrevidos, talentosos, incansables y comprometidos. También es un honor y privilegio trabajar bajo la guía y amparo de un Consejo Directivo constituido por colegas profesionistas que comparten las aspiraciones y pasión de Proyecto Fronterizo y estàn incondicionalmente a nuestra disposiciòn, asesorando y asegurando la rectitud de nuestro rumbo.</p>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m12 l12">
      <p class="no-margin">Confío que este sueño es posible porque a lo largo de este camino veo cómo mucha gente, particularmente los jóvenes, se une a esta causa y acciona por sí misma, colaborando entre sí y con la naturaleza que los rodea. Estoy segura de que ésto es la base para el cambio que se requiere para transitar hacia un mundo mejor.</p>
    </div>
  </div>
</div>